<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KriteriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('kriterias')->insert([
            [
                'id' => 'KRT-001',
                'kriteria' => 'Penggunaan logo BerAKHLAK dan tagar Bangga Melayani Bangsa pada media sosial',
                'deskripsi' => 'Penggunaan logo BerAKHLAK dan tagar Bangga Melayani Bangsa pada media sosial, latar virtual, twibbon, bahan paparan, dan lain-lain',
                'id_poin' => 'PN-001',
                'id_sub_kriteria' => 'SUB-001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-002',
                'kriteria' => 'Penggunaan logo BerAKHLAK dan tagar Bangga Melayani Bangsa pada latar virtual',
                'deskripsi' => 'Penggunaan logo BerAKHLAK dan tagar Bangga Melayani Bangsa pada media sosial, latar virtual, twibbon, bahan paparan, dan lain-lain',
                'id_poin' => 'PN-001',
                'id_sub_kriteria' => 'SUB-001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-003',
                'kriteria' => 'Penggunaan logo BerAKHLAK dan tagar Bangga Melayani Bangsa pada twibbon',
                'deskripsi' => 'Penggunaan logo BerAKHLAK dan tagar Bangga Melayani Bangsa pada media sosial, latar virtual, twibbon, bahan paparan, dan lain-lain',
                'id_poin' => 'PN-001',
                'id_sub_kriteria' => 'SUB-001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-004',
                'kriteria' => 'Penggunaan logo BerAKHLAK dan tagar Bangga Melayani Bangsa pada bahan paparan',
                'deskripsi' => 'Penggunaan logo BerAKHLAK dan tagar Bangga Melayani Bangsa pada media sosial, latar virtual, twibbon, bahan paparan, dan lain-lain',
                'id_poin' => 'PN-001',
                'id_sub_kriteria' => 'SUB-001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-005',
                'kriteria' => 'Penggunaan logo BerAKHLAK dan tagar Bangga Melayani Bangsa pada dan lain-lain',
                'deskripsi' => 'Penggunaan logo BerAKHLAK dan tagar Bangga Melayani Bangsa pada media sosial, latar virtual, twibbon, bahan paparan, dan lain-lain',
                'id_poin' => 'PN-001',
                'id_sub_kriteria' => 'SUB-001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-006',
                'kriteria' => 'Penyisipan informasi BerAKHLAK dan Bangga Melayani Bangsa dalam setiap kegiatan seperti apel, rapat koordinasi/pertemuan, sosialisasi',
                'deskripsi' => 'Penyisipan informasi BerAKHLAK dan Bangga Melayani Bangsa dalam setiap kegiatan seperti apel, rapat koordinasi/pertemuan, sosialisasi, dan lain-lain',
                'id_poin' => 'PN-002',
                'id_sub_kriteria' => 'SUB-002',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-007',
                'kriteria' => 'Penyisipan informasi BerAKHLAK dan Bangga Melayani Bangsa dalam setiap kegiatan lainnya',
                'deskripsi' => 'Penyisipan informasi BerAKHLAK dan Bangga Melayani Bangsa dalam setiap kegiatan seperti apel, rapat koordinasi/pertemuan, sosialisasi, dan lain-lain',
                'id_poin' => 'PN-002',
                'id_sub_kriteria' => 'SUB-002',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-008',
                'kriteria' => 'Penulisan panduan perilaku BerAKHLAK dalam konten media sosial',
                'deskripsi' => 'Penulisan panduan perilaku BerAKHLAK dalam konten media sosial, media elektronik, dan media lainnya',
                'id_poin' => 'PN-001',
                'id_sub_kriteria' => 'SUB-003',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-009',
                'kriteria' => 'Penulisan panduan perilaku BerAKHLAK dalam konten media elektronik',
                'deskripsi' => 'Penulisan panduan perilaku BerAKHLAK dalam konten media sosial, media elektronik, dan media lainnya',
                'id_poin' => 'PN-001',
                'id_sub_kriteria' => 'SUB-003',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id' => 'KRT-010',
                'kriteria' => 'Penulisan panduan perilaku BerAKHLAK dalam konten media lainnya',
                'deskripsi' => 'Penulisan panduan perilaku BerAKHLAK dalam konten media sosial, media elektronik, dan media lainnya',
                'id_poin' => 'PN-001',
                'id_sub_kriteria' => 'SUB-003',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-011',
                'kriteria' => 'Penulisan panduan perilaku BerAKHLAK dalam konten media lainnya',
                'deskripsi' => 'Penulisan panduan perilaku BerAKHLAK dalam konten media sosial, media elektronik, dan media lainnya',
                'id_poin' => 'PN-001',
                'id_sub_kriteria' => 'SUB-003',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-012',
                'kriteria' => 'Penulisan panduan perilaku BerAKHLAK dalam konten media lainnya',
                'deskripsi' => 'Penulisan panduan perilaku BerAKHLAK dalam konten media sosial, media elektronik, dan media lainnya',
                'id_poin' => 'PN-001',
                'id_sub_kriteria' => 'SUB-003',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-013',
                'kriteria' => 'Pemutaran video panduan perilaku BerAKHLAK di media sosial',
                'deskripsi' => 'Pemutaran video panduan perilaku BerAKHLAK di media sosial, media elektronik dan media lainnya',
                'id_poin' => 'PN-002',
                'id_sub_kriteria' => 'SUB-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-014',
                'kriteria' => 'Pemutaran video panduan perilaku BerAKHLAK di media elektronik',
                'deskripsi' => 'Pemutaran video panduan perilaku BerAKHLAK di media sosial, media elektronik dan media lainnya',
                'id_poin' => 'PN-002',
                'id_sub_kriteria' => 'SUB-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [ 
                'id' => 'KRT-015',
                'kriteria' => 'Pemutaran video panduan perilaku BerAKHLAK di media lainnya',
                'deskripsi' => 'Pemutaran video panduan perilaku BerAKHLAK di media sosial, media elektronik dan media lainnya',
                'id_poin' => 'PN-002',
                'id_sub_kriteria' => 'SUB-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-016',
                'kriteria' => 'Pemutaran video panduan perilaku BerAKHLAK di media lainnya',
                'deskripsi' => 'Pemutaran video panduan perilaku BerAKHLAK di media sosial, media elektronik dan media lainnya',
                'id_poin' => 'PN-002',
                'id_sub_kriteria' => 'SUB-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-017',
                'kriteria' => 'Pemberian apresiasi atau hal-hal lain kepada pegawai ASN sebagai bentuk banggga melayani bangsa',
                'deskripsi' => 'Pemberian apresiasi atau hal-hal lain kepada pegawai ASN sebagai bentuk banggga melayani bangsa',
                'id_poin' => 'PN-003',
                'id_sub_kriteria' => 'SUB-005',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-018',
                'kriteria' => 'Pembacaan Core Values ASN BerAKHLAK',
                'deskripsi' => 'Pembacaan Core Values ASN BerAKHLAK',
                'id_poin' => 'PN-002',
                'id_sub_kriteria' => 'SUB-006',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-019',
                'kriteria' => 'Pembacaan Core Values ASN BerAKHLAK',
                'deskripsi' => 'Pembacaan Core Values ASN BerAKHLAK',
                'id_poin' => 'PN-002',
                'id_sub_kriteria' => 'SUB-006',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id' => 'KRT-020',
                'kriteria' => 'Pembacaan Core Values ASN BerAKHLAK',
                'deskripsi' => 'Pembacaan Core Values ASN BerAKHLAK',
                'id_poin' => 'PN-002',
                'id_sub_kriteria' => 'SUB-006',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'KRT-021',
                'kriteria' => 'Pembacaan Core Values ASN BerAKHLAK',
                'deskripsi' => 'Pembacaan Core Values ASN BerAKHLAK',
                'id_poin' => 'PN-002',
                'id_sub_kriteria' => 'SUB-006',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
