<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 'USR-001',
                'nama' => 'super admin',
                'email' => 'superadmin@gmail.com',
                'username' => 'super admin',
                'password' => Hash::make('superadmin123'), // ganti sesuai kebutuhan
                'id_opd' => null,
                'id_peran' => 'PRN-001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-002',
                'nama' => 'admin',
                'email' => 'admin@gmail.com',
                'username' => 'admin',
                'password' => Hash::make('admin1233456'),
                'id_opd' => null,
                'id_peran' => 'PRN-002',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-003',
                'nama' => 'tim verifikasi',
                'email' => 'timver@gmail.com',
                'username' => 'tim verifikasi',
                'password' => Hash::make('timverifikasi1234'),
                'id_opd' => null,
                'id_peran' => 'PRN-003',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-004',
                'nama' => 'BADAN KEPEGAWAIAN DAERAH',
                'email' => 'BKD@gmail.com',
                'username' => 'BKD',
                'password' => Hash::make('BKD12345'),
                'id_opd' => 'OPD-001',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-005',
                'nama' => 'BADAN KESATUAN BANGSA DAN POLITIK',
                'email' => 'BKBP@gmail.com',
                'username' => 'BKBP',
                'password' => Hash::make('BKBP12345'),
                'id_opd' => 'OPD-002',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-006',
                'nama' => 'BADAN PENANGGULANGAN BENCANA DAERAH',
                'email' => 'BPBD@gmail.com',
                'username' => 'BPBD',
                'password' => Hash::make('BPBD12345'),
                'id_opd' => 'OPD-003',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-007',
                'nama' => 'BADAN PENDAPATAN DAERAH',
                'email' => 'BPD@gmail.com',
                'username' => 'BPD',
                'password' => Hash::make('BPD12345'),
                'id_opd' => 'OPD-003',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-008',
                'nama' => 'BADAN PENELITIAN DAN PENGEMBANGAN',
                'email' => 'BPDP@gmail.com',
                'username' => 'BPDP',
                'password' => Hash::make('BPDP12345'),
                'id_opd' => 'OPD-003',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-009',
                'nama' => 'BADAN PENGELOLAAN KEUANGAN DAN ASET DAERAH',
                'email' => 'BPKDAD@gmail.com',
                'username' => 'BPKDAD',
                'password' => Hash::make('BPKDAD12345'),
                'id_opd' => 'OPD-003',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-010',
                'nama' => 'BADAN PENGEMBANGAN SUMBER DAYA MANUSIA',
                'email' => 'BPSDM@gmail.com',
                'username' => 'BPSDM',
                'password' => Hash::make('BPSDM12345'),
                'id_opd' => 'OPD-003',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'id' => 'USR-011',
                'nama' => 'BADAN PENGHUBUNG',
                'email' => 'BPHBG@gmail.com',
                'username' => 'BPHBG',
                'password' => Hash::make('BPHBG12345'),
                'id_opd' => 'OPD-008',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-012',
                'nama' => 'BADAN PERENCANAAN PEMBANGUNAN DAERAH',
                'email' => 'BPPD@gmail.com',
                'username' => 'BPPD',
                'password' => Hash::make('BPPD12345'),
                'id_opd' => 'OPD-009',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-013',
                'nama' => 'DINAS ARSIP DAN PERPUSTAKAAN',
                'email' => 'DAP@gmail.com',
                'username' => 'DAP',
                'password' => Hash::make('DAP12345'),
                'id_opd' => 'OPD-010',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-014',
                'nama' => 'DINAS ENERGI DAN SUMBER DAYA MINERAL',
                'email' => 'DESDM@gmail.com',
                'username' => 'DESDM',
                'password' => Hash::make('DESDM12345'),
                'id_opd' => 'OPD-011',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-015',
                'nama' => 'DINAS KEBUDAYAAN DAN PARIWISATA',
                'email' => 'DKDP@gmail.com',
                'username' => 'DKDP',
                'password' => Hash::make('DKDP12345'),
                'id_opd' => 'OPD-012',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-016',
                'nama' => 'DINAS KEHUTANAN',
                'email' => 'DKHTN@gmail.com',
                'username' => 'DKHTN',
                'password' => Hash::make('DKHTN12345'),
                'id_opd' => 'OPD-013',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-017',
                'nama' => 'DINAS KESEHATAN',
                'email' => 'DKSTN@gmail.com',
                'username' => 'DKSTN',
                'password' => Hash::make('DKSTN12345'),
                'id_opd' => 'OPD-014',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-018',
                'nama' => 'DINAS KETAHANAN PANGAN DAN PETERNAKAN',
                'email' => 'DKPDP@gmail.com',
                'username' => 'DKPDP',
                'password' => Hash::make('DKPDP12345'),
                'id_opd' => 'OPD-015',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-019',
                'nama' => 'DINAS KOMUNIKASI, INFORMATIKA DAN STATISTIK',
                'email' => 'DKIDS@gmail.com',
                'username' => 'DKIDS',
                'password' => Hash::make('DKIDS12345'),
                'id_opd' => 'OPD-016',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-020',
                'nama' => 'DINAS KOPERASI DAN USAHA KECIL DAN MENENGAH',
                'email' => 'DKUKDM@gmail.com',
                'username' => 'DKUKDM',
                'password' => Hash::make('DKUKDM12345'),
                'id_opd' => 'OPD-017',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-021',
                'nama' => 'DINAS LINGKUNGAN HIDUP',
                'email' => 'DLH@gmail.com',
                'username' => 'DLH',
                'password' => Hash::make('DLH12345'),
                'id_opd' => 'OPD-018',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-022',
                'nama' => 'DINAS PEKERJAAN UMUM DAN PENATAAN RUANG',
                'email' => 'DPUPR@gmail.com',
                'username' => 'DPUPR',
                'password' => Hash::make('DPUPR12345'),
                'id_opd' => 'OPD-019',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-023',
                'nama' => 'DINAS PEMBERDAYAAN MASYARAKAT DAN DESA',
                'email' => 'DPMDD@gmail.com',
                'username' => 'DPMDD',
                'password' => Hash::make('DPMDD12345'),
                'id_opd' => 'OPD-020',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-024',
                'nama' => 'DINAS PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK',
                'email' => 'DPPPA@gmail.com',
                'username' => 'DPPPA',
                'password' => Hash::make('DPPPA12345'),
                'id_opd' => 'OPD-021',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-025',
                'nama' => 'DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU',
                'email' => 'DPMDPTSP@gmail.com',
                'username' => 'DPMDPTSP',
                'password' => Hash::make('DPMDPTSP12345'),
                'id_opd' => 'OPD-022',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-026',
                'nama' => 'DINAS PENDIDIKAN',
                'email' => 'DPDKN@gmail.com',
                'username' => 'DPDKN',
                'password' => Hash::make('DPDKN12345'),
                'id_opd' => 'OPD-023',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-027',
                'nama' => 'DINAS PERDAGANGAN DAN PERINDUSTRIAN',
                'email' => 'DPDP@gmail.com',
                'username' => 'DPDP',
                'password' => Hash::make('DPDP12345'),
                'id_opd' => 'OPD-024',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-028',
                'nama' => 'DINAS PERHUBUNGAN',
                'email' => 'DPHBG@gmail.com',
                'username' => 'DPHBG',
                'password' => Hash::make('DPHBG12345'),
                'id_opd' => 'OPD-025',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-029',
                'nama' => 'DINAS PERIKANAN DAN KELAUTAN',
                'email' => 'DPKL@gmail.com',
                'username' => 'DPKL',
                'password' => Hash::make('DPKL12345'),
                'id_opd' => 'OPD-026',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-030',
                'nama' => 'DINAS PERKEBUNAN',
                'email' => 'DPBN@gmail.com',
                'username' => 'DPBN',
                'password' => Hash::make('DPBN12345'),
                'id_opd' => 'OPD-027',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-031',
                'nama' => 'DINAS PERTANIAN',
                'email' => 'DPTRN@gmail.com',
                'username' => 'DPTRN',
                'password' => Hash::make('DPTRN12345'),
                'id_opd' => 'OPD-028',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-032',
                'nama' => 'DINAS SOSIAL',
                'email' => 'DSSL@gmail.com',
                'username' => 'DSSL',
                'password' => Hash::make('DSSL12345'),
                'id_opd' => 'OPD-029',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-033',
                'nama' => 'DINAS TENAGA KERJA DAN TRANSMIGRASI',
                'email' => 'DTKT@gmail.com',
                'username' => 'DTKT',
                'password' => Hash::make('DTKT12345'),
                'id_opd' => 'OPD-030',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-034',
                'nama' => 'DINAS TRANSMIGRASI DAN ENERGI',
                'email' => 'DTE@gmail.com',
                'username' => 'DTE',
                'password' => Hash::make('DTE12345'),
                'id_opd' => 'OPD-031',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-035',
                'nama' => 'DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL',
                'email' => 'DKPS@gmail.com',
                'username' => 'DKPS',
                'password' => Hash::make('DKPS12345'),
                'id_opd' => 'OPD-032',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-036',
                'nama' => 'INSPEKTORAT DAERAH',
                'email' => 'ISD@gmail.com',
                'username' => 'ISD',
                'password' => Hash::make('ISD12345'),
                'id_opd' => 'OPD-033',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-037',
                'nama' => 'RUMAH SAKIT UMUM DAERAH',
                'email' => 'RSUD@gmail.com',
                'username' => 'RSUD',
                'password' => Hash::make('RSUD12345'),
                'id_opd' => 'OPD-034',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-038',
                'nama' => 'SATUAN POLISI PAMONG PRAJA',
                'email' => 'SPPP@gmail.com',
                'username' => 'SPPP',
                'password' => Hash::make('SPPP12345'),
                'id_opd' => 'OPD-035',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-039',
                'nama' => 'SEKRETARIAT DPRD',
                'email' => 'SDPRD@gmail.com',
                'username' => 'SDPRD',
                'password' => Hash::make('SDPRD12345'),
                'id_opd' => 'OPD-036',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-040',
                'nama' => 'SEKRETARIAT DAERAH',
                'email' => 'SDRH@gmail.com',
                'username' => 'SDRH',
                'password' => Hash::make('SDRH12345'),
                'id_opd' => 'OPD-037',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-041',
                'nama' => 'DINAS OLAHRAGA DAN PEMUDA',
                'email' => 'DODP@gmail.com',
                'username' => 'DODP',
                'password' => Hash::make('DODP12345'),
                'id_opd' => 'OPD-038',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-042',
                'nama' => 'DINAS PERUMAHAN RAKYAT DAN KAWASAN PERMUKIMAN',
                'email' => 'DPRDKP@gmail.com',
                'username' => 'DPRDKP',
                'password' => Hash::make('DPRDKP12345'),
                'id_opd' => 'OPD-039',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-043',
                'nama' => 'DINAS KELAUTAN DAN PERIKANAN',
                'email' => 'DKLP@gmail.com',
                'username' => 'DKLP',
                'password' => Hash::make('DKLP12345'),
                'id_opd' => 'OPD-040',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-044',
                'nama' => 'DINAS HORTIKULTURA',
                'email' => 'DPDH@gmail.com',
                'username' => 'DPDH',
                'password' => Hash::make('DPDH12345'),
                'id_opd' => 'OPD-041',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-045',
                'nama' => 'DINAS PELAYANAN PUBLIK',
                'email' => 'DPP@gmail.com',
                'username' => 'DPP',
                'password' => Hash::make('DPP12345'),
                'id_opd' => 'OPD-042',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-046',
                'nama' => 'DINAS PERTANIAN TANAMAN PANGAN',
                'email' => 'DPTP@gmail.com',
                'username' => 'DPTP',
                'password' => Hash::make('DPTP12345'),
                'id_opd' => 'OPD-043',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-047',
                'nama' => 'DINAS TATA RUANG DAN BANGUNAN',
                'email' => 'DTRB@gmail.com',
                'username' => 'DTRB',
                'password' => Hash::make('DTRB12345'),
                'id_opd' => 'OPD-044',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-048',
                'nama' => 'DINAS TRANSPORTASI',
                'email' => 'DTRSP@gmail.com',
                'username' => 'DTRSP',
                'password' => Hash::make('DTRSP12345'),
                'id_opd' => 'OPD-045',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-049',
                'nama' => 'DINAS KEBERSIHAN DAN KEINDAHAN',
                'email' => 'DKDK@gmail.com',
                'username' => 'DKDK',
                'password' => Hash::make('DKDK12345'),
                'id_opd' => 'OPD-046',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-050',
                'nama' => 'DINAS PENGELOLAAN SUMBER DAYA AIR',
                'email' => 'DPSDA@gmail.com',
                'username' => 'DPSDA',
                'password' => Hash::make('DPSDA12345'),
                'id_opd' => 'OPD-047',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-051',
                'nama' => 'DINAS PERIZINAN',
                'email' => 'DPZN@gmail.com',
                'username' => 'DPZN',
                'password' => Hash::make('DPZN12345'),
                'id_opd' => 'OPD-048',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-052',
                'nama' => 'DINAS PERENCANAAN',
                'email' => 'DPRCN@gmail.com',
                'username' => 'DPRCN',
                'password' => Hash::make('DPRCN12345'),
                'id_opd' => 'OPD-049',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-053',
                'nama' => 'DINAS KEMASYARAKATAN',
                'email' => 'DKMSY@gmail.com',
                'username' => 'DKMSY',
                'password' => Hash::make('DKMSY12345'),
                'id_opd' => 'OPD-050',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'USR-054',
                'nama' => 'DINAS TEKNOLOGI INFORMASI',
                'email' => 'DTI@gmail.com',
                'username' => 'DTI',
                'password' => Hash::make('DTI12345'),
                'id_opd' => 'OPD-051',
                'id_peran' => 'PRN-004',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
